package miniplc0java.instruction;

public enum Operation {
    NOP,PUSH,POP,POPN,DUP,LOCA,ARGA,GLOBA,LOAD8,LOAD16,LOAD32,LOAD64,
    STORE8,STORE16,STORE32,STORE64,ALLOC,FREE,STACK_ALLOC,

    ADD_I,SUB_I,MUL_I,DIV_I,
    ADD_F,SUB_F,MUL_F,DIV_F,DIV_U,
    SHL,SHR,AND,OR,XOR,NOT,

    CMP_I,CMP_U,CMP_F,
    NEG_I,NEG_F,

    ITOF,FTOI,

    SHRL,SET_LT,SET_GT,

    BR,BR_FALSE, BR_TRUE,CALL,RET,CALL_NAME,
    SCAN_I,SCAN_C,SCAN_F,
    PRINT_I,PRINT_C,PRINT_F,PRINT_S,PRINT_LN,
    PANIC,
}
